default: &default
  dispatchers:
    - polling_interval: 5
      batch_size: 500
      recurring_tasks:
        synchronization_job:
          class: SynchronizationJob
          args: []
          schedule: every 10 minutes
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
