name: CI

on:
  schedule:
    - cron: "0 2 * * *" # daily @ 02:00

jobs:
  export:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/mssql/server:2022-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Convert ft export into zipped json
        run: bin/rails backup:export

      - name: Create release on GitHub
        run: gh release create "v$(date +%Y.%m.%d)" './tmp/storage/export.tar.gz#Daily JSON export' --generate-notes
