name: Export

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 2 * * *" # daily @ 02:00

jobs:
  export:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Hunter2!
          MSSQL_PID: Express
        ports:
          - 1433:1433
        volumes:
          - /tmp/storage:/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Download and re-export daily oda backup
        run: ruby script/export.rb

      - name: Create release on GitHub
        run: gh release create "v$(date +%Y.%m.%d)" './tmp/storage/daily.zip#Daily JSON export' --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
