name: Export

on:
  schedule:
    - cron: "0 2 * * *" # daily @ 02:00

permissions:
   contents: write

jobs:
  export:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Hunter2!
          MSSQL_PID: Express
        ports:
          - 1433:1433
        volumes:
          - /tmp:/tmp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Download and re-export daily oda backup
        run: ruby script/export.rb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
